# -*- coding: utf-8 -*-
"""Step 3 - Analysis Speed below 25MBps - Python_Ookla Mobile Q3 2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PHxxSSYXqr1bczS8cspn_Aqp3tNYMRuT

### Step 3: Analyzing download speeds (Ref: https://www.kaggle.com/code/dhruvildave/starter-ookla-internet-speed-dataset/notebook)

##### 1. Import relevant library
"""

from datetime import datetime

import geopandas as gp
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import folium
import streamlit as st

from folium import Choropleth
from shapely.geometry import Point
from adjustText import adjust_text

import fiona

##### 2. Load dataset

df=gp.read_file("/content/Malaysia_Mobile_2022_Q3.geojson")

df.head()

df = df[["quadkey","avg_d_kbps","avg_u_kbps","avg_lat_ms","tests","devices","geometry","avg_d_mbps","avg_u_mbps"]]

df.head()

df.crs

"""## Using Folium"""

df.dtypes

m = folium.Map(location=[4.1093195,109.45547499999998],tiles='openstreetmap', zoom_start=6.2)
m

d = df[df.avg_d_mbps <= 25].set_index("quadkey")

Choropleth(
    geo_data=d.geometry.__geo_interface__,
    data=d.avg_d_mbps,
    legend_name="Average Download speed",
    fill_color="RdPu",
    opacity=1.5,
    highlight=True,
    key_on="feature.id",
).add_to(m)

m

"""##### 9. Save the file"""

##Final_gdf_data.to_csv("Final_Ookla_Fixed(MYS)_2020_Q2.csv",index=False,header=True)

# save the geodataframe as a geojson file
##gdf.to_file("output.geojson", driver='GeoJSON')

